# Generated by Django 3.1.1 on 2020-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_hostscan_add_deltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='label',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
